### PR TITLE
umirbyek

### PR DESCRIPTION
**Pull request by umirbyek**
no title

### CODE REVIEW

**Review by biligunb — CHANGES_REQUESTED** [review]
resume, git notes is NOT FOUND?

**Comment by umirbyek** [comment]
[resume_umirbyek.pdf](https://github.com/biligunb/dev101/files/10815021/resume_umirbyek.pdf)

**Comment by umirbyek** [comment]
now submitted resume file

**Comment by biligunb** [comment]
@umirbyek GIT рүүгээ нэмнэ ээ.
энд comment-д биш

**Review by biligunb — APPROVED** [review]
TEMP

**Pull request merged**
